### ISSUE TITLE
A question about Tab.5 in Ablation Study

### ISSUE THREAD

**Issue by Trent-tangtao** [zhyever/SimIPU#3]
Thanks for your excellent work first!   I have a question about Tab.5 in Ablation Study.   Why  "Scratch" equals "SimIPU w/o inter-module ", which means that the intra-module is useless?

**Comment by zhyever** [comment]
Hi,

Thanks for your attention to our work. The key losses in SimIPU contain two parts: the intro-loss and the inter-loss. Note the gradient crop operation presented in the paper and discussed in Issue #2, and keep in mind that the goal of SimIPU is to learn spatial-aware **visual** representation. SimIPU w/o inter means the model is trained only by intro-loss. It can help the point cloud branch learn the spatial-aware representation. However, since there is no inter-loss, the image branch has no gradient and can learn nothing. When we transfer it (only img encoder) to downstream tasks, it is reasonable that we will get similar results to the scratch model. This ablation shows the inter-module is crucial to transfer knowledge while the "SimIPU w/o intra-module" demonstrates the effectiveness of the intra-module.

If there are still problems, feel free to contact me.
